// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrar.Data;

#nullable disable

namespace Migrar.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240108122707_sixthmigration")]
    partial class sixthmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Migrar.Model.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_destino");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("foto_destino");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("local_destino");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_destino");

                    b.HasKey("Id");

                    b.ToTable("destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Foto = "https://images.pexels.com/photos/1850619/pexels-photo-1850619.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Local = "Paris, França",
                            Valor = 2000.00m
                        },
                        new
                        {
                            Id = 2,
                            Foto = "https://images.pexels.com/photos/2341830/pexels-photo-2341830.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Local = "Tóquio, Japão",
                            Valor = 2500.00m
                        },
                        new
                        {
                            Id = 3,
                            Foto = "https://images.pexels.com/photos/2876407/pexels-photo-2876407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Local = "Rio de Janeiro, Brasil",
                            Valor = 1000.00m
                        },
                        new
                        {
                            Id = 4,
                            Foto = "https://images.pexels.com/photos/40142/new-york-skyline-manhattan-hudson-40142.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Local = "Nova York, EUA",
                            Valor = 3000.00m
                        },
                        new
                        {
                            Id = 5,
                            Foto = "https://images.pexels.com/photos/2193300/pexels-photo-2193300.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Local = "Sydney, Austrália",
                            Valor = 2800.00m
                        },
                        new
                        {
                            Id = 6,
                            Foto = "https://images.pexels.com/photos/136721/pexels-photo-136721.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Local = "Cidade do Cabo, África do Sul",
                            Valor = 2200.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
